name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5

      - name: Run linters
        run: make check

      - name: Run unit tests
        run: make test-unit

      - run: sudo sh -c "echo 2097152 >> /proc/sys/fs/aio-max-nr"

      - name: Run integration suite
        run: make test-integration-scylla

      - name: Run CCM integration suite
        run: TEST_INTEGRATION_TAGS="ccm gocql_debug" make test-integration-scylla

