name: Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - "*.md"
      - "docs/**"
      - .github/workflows/docs-*
      - .github/workflows/bench-tests.yml
      - .github/workflows/extended-ci-longevity-large-partitions-with-network-nemesis-1h-test.yml
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "*.md"
      - "docs/**"
      - .github/workflows/docs-*
      - .github/workflows/bench-tests.yml
      - .github/workflows/extended-ci-longevity-large-partitions-with-network-nemesis-1h-test.yml

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6

      - name: Run linters
        run: make check

      - name: Run unit tests
        run: make test-unit

      - run: sudo sh -c "echo 2097152 >> /proc/sys/fs/aio-max-nr"

      - name: Run integration suite
        run: make test-integration-scylla

      - name: Run CCM integration suite
        run: TEST_INTEGRATION_TAGS="ccm gocql_debug" make test-integration-scylla

